# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 12:57:33 2019

@author: lennie
"""

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest /test